# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='email',
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
