# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170106_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
