# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
