# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_project_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=200)),
                ('description', models.CharField(default='default', max_length=200)),
            ],
        ),
    ]
