# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170406_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpageproject',
            name='author',
        ),
        migrations.DeleteModel(
            name='FrontPageProject',
        ),
    ]
